### ISSUE TITLE
Server with "npm start" not starting

### ISSUE THREAD

**Issue by JensUweB** [lenneTech/nest-server-starter#5]
**After installing the server over the cli on a windows 10 computer and installing the dependencies,  npm start failed:**

PS C:\Projekte\Web\le-nest-backend> npm start

- le-nest-backend@0.0.1 start C:\Projekte\Web\le-nest-backend
- grunt

Running "clean:buildFolder" (clean) task
-- 1 path cleaned.

Running "bgShell:tsc" (bgShell) task
-- Der Befehl "node_modules" ist entweder falsch geschrieben oder
-- konnte nicht gefunden werden.
-- Error: Command failed: node_modules/.bin/tsc -p tsconfig.build.json

Running "sync:templates" (sync) task
Copying src\templates\welcome.ejs -> dist\templates\welcome.ejs

Running "bgShell:tscWatch" (bgShell) task

Running "bgShell:pm2" (bgShell) task
-- Der Befehl "node_modules" ist entweder falsch geschrieben oder
-- konnte nicht gefunden werden.
-- Error: Command failed: node_modules/.bin/tsc -w -p tsconfig.build.json
-- Der Befehl "node_modules" ist entweder falsch geschrieben oder
-- konnte nicht gefunden werden.
-- Error: Command failed: node_modules/.bin/pm2 startOrRestart pm2.config.js

Running "watch" task
Waiting...

**Comment by kaihaase** [comment]
Resolved by 187dd0341124d4dbf90d2e7c4a25c0eb38d76afd
